### ISSUE TITLE
我在训练第一阶段的时候，loss一直不变是什么原因呢

### ISSUE THREAD

**Issue by weiyingxue** [wangyongqi558/MMP_OV_VidVRD#10]
我在训练第一阶段的时候，loss一直不变是什么原因呢 ，bs=32,其他参数跟原文一致

_Originally posted by @weiyingxue in https://github.com/wangyongqi558/MMP_OV_VidVRD/issues/5#issuecomment-2119570411_

**Comment by PeiMing1998** [comment]
哥们，model parameter require grad没true吧

**Comment by weiyingxue** [comment]
好的，谢谢

**Comment by weiyingxue** [comment]
朋友能加个联系方式吗
