### ISSUE TITLE
关于clip特征 rel bbox mot特征的计算方式以及train objectpair 的选取方式的几个问题

### ISSUE THREAD

**Issue by PeiMing1998** [wangyongqi558/MMP_OV_VidVRD#6]
您好，打扰一下我想咨询一下下列问题
(1) object pair之间的rel feature(42d)/box feature(42d)/mot_feature(42d)如何计算
(2)train数据ground truth rel instance共计25917个  如果限制sub obj pred都为base类 共计15531 个， 如果我将所有relinstance中相同stid otid的记录合并 且考虑或者不考虑持续有关系片段合并 最终会得到 9935/13405个 object pair, 但是始终没有得到提供数据的10156个object pair 所以我想咨询下您是怎么采样train数据中的object pair
(3)clip feature 是不是要如原文中描述的一样是将图片非object部分填0 然后encode 得到的呢？并且在30帧的片段中采样那一张图片得到feature呢？以及很多工作segment的帧的序号是0 29,15 44,30 59这样有重叠的，您的工作中segment对应帧的序号是否也是这样还是说不考虑重叠 0 29,30 59,60 89
非常感谢！！！

**Comment by PeiMing1998** [comment]
box feature 似乎是 xyxy cxcywh normalize后的结果不知是否正确

**Comment by wangyongqi558** [comment]
后续会上传特征提取的代码，可供细节的参考

**Comment by wangyongqi558** [comment]
注意把文件中CLIP backbone更换为ViT-B/16
