### ISSUE TITLE
谢谢您的文件，，但是好像缺失vidor的prior.pkl文件

### ISSUE THREAD

**Issue by weiyingxue** [wangyongqi558/MMP_OV_VidVRD#8]
谢谢您的文件，，但是好像缺失vidor的prior.pkl文件

_Originally posted by @weiyingxue in https://github.com/wangyongqi558/MMP_OV_VidVRD/issues/4#issuecomment-2097819606_

**Comment by wangyongqi558** [comment]
已添加
