### ISSUE TITLE
你好，请问如何提取数据集的xx_xx_30_box和xx_xx_30_ptm？

### ISSUE THREAD

**Issue by weiyingxue** [wangyongqi558/MMP_OV_VidVRD#9]
在特征提取文件中没有给出

**Comment by wangyongqi558** [comment]
现在的特征提取文件把所有的特征都提取在了xx_xx_30文件夹中，只需修改dataset.py文件中的getitem为
def __getitem__(self, index):

        pair_path = self.path_list[index]
        data = pickle.load(open(pair_path,"rb"))
        # pair_data_rel = pickle.load(open(pair_path[0],"rb"))
        # pair_data_ptm = pickle.load(open(pair_path[1],"rb"))
        pair_feats = data[0]
        item = {}
        for type_ in pair_feats:
            item[type_] = np.array(pair_feats[type_])
        if self.split == 'train':
            ## for bce
            pair_data = data[1][2]
            pair_label = np.zeros((len(pair_data), self.pre_num),)
            for clip_idx, clip_label in enumerate(pair_data):
                tmp_label = np.zeros(self.pre_num,)
                if len(clip_label) > 0:
                    tmp_label[clip_label] = 1
                pair_label[clip_idx] = tmp_label
            item['pre_label'] = pair_label
            item['sbj_label'] = data[1][0]
            item['obj_label'] = data[1][1]

            # for ce
            # pair_label = np.zeros(len(pair_data[1]))
            # for clip_idx, clip_label in enumerate(pair_data[1]):
            #     if len(clip_label) > 0:
            #         pair_label[clip_idx] = random.choice(clip_label)
            #     else:
            #         pair_label[clip_idx] = -1
            # item['label'] = pair_label          
        else:
            item['vid'] = pair_path.split('/')[-1].split('.')[0][:-7]
            item['pair_data'] = data[1]
        
        return item
